language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached
 - rabbitmq

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database amcat;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_SETTINGS_MODULE=settings
 - export TRAVIS=true
 - export AMCAT_ES_LEGACY_HASH=0
 - export PYTHONPATH=
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 2 # Give framebuffer some time to start

install:
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - sudo service rabbitmq-server start

 # Elasticsearch
 - wget --no-check-certificate https://hmbastiaan.nl/martijn/amcat/hitcount.jar
 - wget --no-check-certificate https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.3.tar.gz -O - | tar xvz
 - cd elasticsearch-1*
 - bin/plugin -install elasticsearch/elasticsearch-lang-python/2.4.1
 - bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.4.2
 - bin/plugin -install mobz/elasticsearch-head
 # I'm absolutely, thorougly annoyed by the syntax below.
 - "tee -a ./config/elasticsearch.yml <<< 'script.disable_dynamic: false'"
 - cd ..
 - ES_CLASSPATH=hitcount.jar elasticsearch-1*/bin/elasticsearch -Des.index.similarity.default.type=nl.vu.amcat.HitCountSimilarityProvider -d
 - pip install -r requirements.txt
 - pip install coverage coveralls
 - celery -A amcat.amcatcelery worker -l DEBUG -Q amcat &
 - npm install -g bower
 - bower install

script:
 - coverage run --source=. --omit=*/migrations/*,settings/* -m amcat.manage test

after_success:
 - coverage report -m
 - coveralls