language: python
python:
  - "2.7"

services:
 - postgresql
 - memcached
 - rabbitmq

virtualenv:
  system_site_packages: true

before_install:
 - psql -c 'create database amcat;' -U postgres
 - export DJANGO_DB_USER=postgres
 - export DJANGO_LOG_LEVEL=WARNING
 - export DJANGO_SETTINGS_MODULE=settings
 - export TRAVIS=true
 - export AMCAT_ES_LEGACY_HASH=0
 - export PYTHONPATH=
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 2 # Give framebuffer some time to start

install:
 - sudo apt-get update
 - cat apt_requirements.txt | tr '\n' ' ' | xargs sudo apt-get install -y
 - sudo service rabbitmq-server start

 # Elasticsearch
 - wget --no-check-certificate https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.1/elasticsearch-2.1.1.deb
 - sudo dpkg -i elasticsearch-2.1.1.deb
 - sudo /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head
 - sudo /usr/share/elasticsearch/bin/plugin install analysis-icu
 - sudo /usr/share/elasticsearch/bin/plugin install amcat/hitcount
 - "sudo tee -a /etc/elasticsearch/elasticsearch.yml <<< 'index.similarity.default.type: hitcountsimilarity'"
 - "sudo tee -a /etc/elasticsearch/elasticsearch.yml <<< 'script.inline: on'"
 - "sudo tee -a /etc/elasticsearch/elasticsearch.yml <<< 'script.update: on'"
 - sudo service elasticsearch stop
 - sudo service elasticsearch start
 - pip install -r requirements.txt
 - pip install coverage coveralls
 - celery -A amcat.amcatcelery worker -l DEBUG -Q amcat &
 - npm install -g bower
 - bower install

script:
 - coverage run --source=. --omit=*/migrations/*,settings/* -m amcat.manage test

after_success:
 - coverage report -m
 - coveralls